apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-todos
  namespace: jagoe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50M
