apiVersion: v1
kind: Pod           
metadata: 
  name: nginx
  labels:
    app: nginx
spec:               
  containers:
  - name: nginx
    image: nginx:latest
    ports:             
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
      host: pinata.infinite-turtles.dev
  tls:
    - hosts:
        - pinata.infinite-turtles.dev
      secretName: pinata-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    kubernetes.io/ingress.class: traefik
spec:                        
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
      host: raspberrypinata
